global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-alerts-payment.yml

scrape_configs:
  - job_name: "payment-orchestrator"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "payment-orchestrator-api:8080"
